#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# routes.yaml or any routing file
app_delete:
    path: /evenementdelete/{id}
    controller: App\Controller\EvenementController::delete
    methods: [DELETE]
