#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# routes.yaml or any routing file
app_delete:
    path: /evenementdelete/{id}
    controller: App\Controller\EvenementController::delete
    methods: [DELETE]
app_evenement_rechercher:
    path: '/evenement/search'
    controller: 'App\Controller\EvenementController::search'
    methods: ['POST']
app_afficher_reservation:
    path: /afficher/reservation
    controller: 'App\Controller\ReserverEventController::show'
    methods: ['GET']

   